spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: Aa000000
  redis:
    host: localhost
    port: 6379
    timeout: 20000
  mail:
    host: smtp.exmail.qq.com
    username: noreply@likly.com.cn
    password: Qq0000
  jackson:
    default-property-inclusion: non_null
  #    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
  transaction:
    rollback-on-commit-failure: true
  application:
    name: final-test
pagehelper:
  auto-dialect: true
  close-conn: true
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: pageNum=page;size=size
logging:
  level:
    cn:
      com:
        likly:
          finalframework:
            test:
              dao:
                mapper: debug
server:
  port: 8080
